apiVersion: v2
name: samba
description: Samba is the standard Windows interoperability suite of programs for Linux and Unix.
type: application
annotations:
  category: Infrastructure
  licenses: Apache-2.0
version: 0.1.3
appVersion: 0.0.1
dependencies:
  - name: samba
    repository: https://stopdenbus.github.io/samba
    version: 0.0.3
    alias: samba
