kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: https
  annotations:
    metallb.io/allow-shared-ip: nginx
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTPS
    port: 8443
    name: https
    tls:
      mode: Terminate
      certificateRefs:
        - name: wildcard-apps
          kind: Secret
    allowedRoutes:
      namespaces:
        from: All
