kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: https
spec:
  infrastructure:
    annotations:
      metallb.io/allow-shared-ip: nginx
      metallb.io/ip-allocated-from-pool: nginx
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTPS
    port: 8443
    name: https
    tls:
      mode: Terminate
      certificateRefs:
        - name: wildcard-apps
          kind: Secret
          group: ''
    allowedRoutes:
      namespaces:
        from: All
