apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypi-packages-pvc
  labels:
    {{- include "pypi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: zfs
  volumeMode: Filesystem