apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pypi-auth
  labels:
    {{- include "pypi.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pypi-auth
    template:
      type: Opaque
      data:
        .htpasswd: "{{ `{{ .htpasswd | toString }}` }}"
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: secrets/data/kubernetes/pypi/pypi
        property: htpasswd
