apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pypi-auth
  labels:
    {{- include "pypi.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pypi-auth
    template:
      type: Opaque
      data:
        {{- $user := "pypi" }}
        {{- $creds := printf "%s" ( htpasswd $user `{{ .pypi }}`) }}
        .htpasswd: {{ $creds }}
    creationPolicy: Owner
  data:
    - secretKey: pypi
      remoteRef:
        key: secrets/data/kubernetes/pypi/pypi
        property: key
