{{- range $namespace, $properties := .Values.namespaces }}
{{- if $properties.docker_dhi_secret }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dhi-secret
  namespace: {{ $namespace }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dhi-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .docker_config_json}}` }}"
    creationPolicy: Owner
  data:
    - secretKey: docker_config_json
      remoteRef:
        key: secrets/data/kubernetes/dhi
        property: dockerconfigjson
{{- end }}
{{- end -}}
