namespaces:
  argocd: {}
  dex: {}
  dungeon: {}
  external-dns:
    docker_dhi_secret: true
  external-secrets: {}
  ingress-nginx: {}
  kgateway-system: {}
  mail: {}
  metallb-system: {}
  monitoring: {}
  mysql: {}
  openebs: {}
  pihole: {}
  reloader: {}
  samba: {}
  stuff: {}
  wishlist: {}
